<a href="https://colab.research.google.com/github/pavan2108/tensorflow/blob/main/introduction_to_tensor_flow_module_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to tensor flow

In [3]:
%tensorflow_version 2.x

In [4]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


#### Creating Tensors

In [12]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(1200, tf.int32)
floating = tf.Variable(2.23, tf.float32)
print(string, number, floating, sep="\n")
print(string.value, number.value, floating.value, sep="\n")

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1200>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.23>
<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>>
<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1200>>
<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.23>>


#### Rank or degree of tensors

In [16]:
tensor_rank1 = tf.Variable(["Test"], tf.string)
tensor_rank2 = tf.Variable([[1,2],[3,4]], tf.int16)

#### small data on rank

            variable string, number, floating is of rank 0
            tensor_ranks1 is of rank 1 as it is of 1d array
            tensor_rank2 is of rank 2 as it is of 2d array

In [17]:
tf.rank(tensor_rank1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [18]:
tf.rank(tensor_rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [19]:
tf.shape(tensor_rank2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [20]:
tensor_rank2.shape

TensorShape([2, 2])

#### Reshape tensors

In [25]:
tensor1 = tf.ones([1, 2, 3])
tensor2 = tf.reshape(tensor1, [3,1, 2])
tensor3 = tf.reshape(tensor1, [3, -1])

In [26]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]], shape=(3, 1, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#### Evaluating tensors

In [28]:
# with tf.Session() as sess:
#     tensor_rank2.eval()