<a href="https://colab.research.google.com/github/pavan2108/tensorflow/blob/main/TensorFlow_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x

In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [5]:
t = tf.zeros([5, 5])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)


In [12]:
print(tf.reshape(t, [5, 1, -1]))

tf.Tensor(
[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]], shape=(5, 1, 5), dtype=float32)
